### ISSUE TITLE
Markdown not respecting line breaks.

### ISSUE THREAD

**Issue by grinfax** [the-mikedavis/doc_gen#21]
Markdown not respecting line breaks. 

http://lisbon.formativejournalism.org/about

**Comment by the-mikedavis** [comment]
@grinfax I think markdown makes you double-newline every time you want a new line

We might be able to make some under the hood changes to make 1 newline be a line break if that's desirable. I threw a couple `<br>`s in there and that seems to give a nice vertical space.
